// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixpzaohmksnngxgfdcrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4cHphb2hta3Nubmd4Z2ZkY3JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMTI3MTgsImV4cCI6MjA2Njg4ODcxOH0.4T_G3YG7G1pk_uL6QyktMMV2oCequ5z2n486AmzhfAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});